name = "pratejra-landing"
compatibility_date = "2024-01-01"
pages_build_output_dir = "build"

[env.production]
routes = [
  { pattern = "/functions/analytics/*", zone_name = "pratejra.build" }
]

[vars]
NODE_VERSION = "18"

[[pages_build_config]]
build_command = "npm run build"
destination_dir = "build"
root_dir = "."
